const PROFILES = [
    {
      name: 'Daredevil',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: DARE_DEVIL,
    },
    {
      name: 'House Of Cards',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: HOUSE_OF_CARDS,
    },
    {
      name: 'Luke Cage',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: LUKE_CAGE,
    },
    {
      name: 'Orange Is The New Black',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: ORANGE_IS_THE_NEW_BLACK,
    },
    {
      name: 'Stranger Things',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: STRANGER_THINGS,
    },
    {
      name: 'Daredevil',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: DARE_DEVIL,
    },
    {
      name: 'House Of Cards',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: HOUSE_OF_CARDS,
    },
    {
      name: 'Luke Cage',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: LUKE_CAGE,
    },
    {
      name: 'Orange Is The New Black',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: ORANGE_IS_THE_NEW_BLACK,
    },
    {
      name: 'StrangerThings',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: STRANGER_THINGS,
    },
    {
      name: 'Dare Devil',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: DARE_DEVIL,
    },
    {
      name: 'House Of Cards',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: HOUSE_OF_CARDS,
    },
    {
      name: 'LukeCage',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: LUKE_CAGE,
    },
    {
      name: 'Orange Is TheNewBlack',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: ORANGE_IS_THE_NEW_BLACK,
    },
    {
      name: 'Stranger Things',
      bio: 'When a young boy vanishes, a small town uncovers a mystery involving a secret experiment, terrify supernatural forces, and one strange little girl',
      mail: 'Winona Ryder, David Harbour, Mathew Modine',
      phone: 'The Duffer Brothers',
      photo: STRANGER_THINGS,
    },
  ];
  
  export default PROFILES;